# Generated by Django 3.2.25 on 2024-11-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='date_write',
            field=models.DateTimeField(),
        ),
    ]
